export const FETCH_TALENT_LANDING = 'FETCH_TALENT_LANDING';
export const FETCH_TALENT_SEARCH = 'FETCH_TALENT_SEARCH';
export const FETCH_TALENT_FEED = 'FETCH_TALENT_FEED';
export const FETCH_TALENT_ATTRIBUTES = 'FETCH_TALENT_ATTRIBUTES';